app/components/Background.tsx
app/components/Box.tsx
app/components/Container.tsx
app/components/Header.tsx
app/components/InfoBox.tsx
app/components/InfoBoxItem.tsx
app/components/PageContent.tsx
app/components/index.ts
app/routes/datenschutz.tsx
app/routes/impressum.tsx
app/routes/kitchensink._index.tsx
app/routes/vorabcheck.$stepID.tsx
app/services/cms/models/basicComponents.ts
app/services/cms/models/formComponents.ts
app/services/cms/models/metaComponents.ts
app/services/cms/models/pageComponents.ts

needs a bit more polishing, but to get the idea...

Add Box component

---

doc/adr/0001-record-any-decisions.md

Introduce ADRs

---

app/services/openSourceLicenses/generate.ts
package-lock.json
package.json

waiting for https://github.com/RSeidelsohn/license-checker-rseidelsohn/issues/95

chore: update license-checker to 4.2.7+

---

.github/actions/parse-content-to-file/create_content_file.py
app/root.tsx
app/routes/beratungshilfe.tsx
app/routes/beratungshilfe.zustaendiges-gericht.auswahl.$PLZ.tsx
app/routes/shared/result.tsx
app/routes/shared/step.tsx
app/services/cms/getStrapiEntryFromApi.ts
app/services/cms/getStrapiEntryFromFile.ts
app/services/cms/index.server.ts
app/services/cms/models/StrapiFileContent.ts
app/services/cms/models/StrapiTranslations.ts
app/services/cms/schemas.ts
tests/unit/services/cms/getStrapiEntryFromApi.test.ts
tests/unit/services/cms/getStrapiEntryFromFile.test.ts

Only merge after https://github.com/digitalservicebund/a2j-rechtsantragstelle-strapi/pull/184

feat: use strapi translations

---

.github/workflows/build-content.yml
.github/workflows/ci-pipeline.yml
.github/workflows/e2e-test.yml
playwright.config.ts
tests/e2e/csrf.spec.ts

WIP feat(sharding): initial prep for playwright sharding

---

app/components/ArraySummary.tsx
playwright.config.ts
tests/e2e/beratungshilfe.formular.spec.ts
tests/e2e/pom/BeratungshilfeFormular.ts
tests/e2e/pom/CourtFinder.ts
tests/e2e/pom/Formular.ts
tests/e2e/pom/Vorabcheck.ts

This branch will add the tests for the flow Beratungshilfe Antrag

E2e tests beratungshilfe formular

---

airports.cjs
app/components/CookieBanner.tsx
app/models/flows/beratungshilfeFormular/__test__/stringReplacements.test.ts
app/routes/geld-einklagen.vorabcheck.partnergericht.ergebnis.$.tsx
app/services/flow/server/buildFlowController.ts
app/services/pdf/beratungshilfe/sections/footer.ts
app/services/pdf/pdf.server.ts
app/services/validation/__test__/buildStepValidator.test.ts
app/services/validation/money/__test__/validateMoney.test.ts
stories/InfoBox.stories.tsx

refactor: code exploration fixes 

---

app/components/FlowNavigation.tsx
app/components/__test__/FlowNavigation.test.tsx
app/models/flows/beratungshilfeFormular/index.ts
app/services/__test__/flowNavigation.test.ts
app/services/flowNavigation.server.ts
app/services/navigation/navState.ts
stories/FlowNavigation.stories.tsx

Mostly replaces subflownavigation & subnavitem with nesting. This was done now to simplify the upcoming restyling

Refactor FlowNavigation

---

app/components/FlowNavigation.tsx
app/routes/shared/components/FormFlowPage.tsx
app/services/flowNavigation.server.ts
app/services/navigation/navState.ts

Depends on https://github.com/digitalservicebund/a2j-rechtsantragstelle/pull/852
look:
Todo:

restyle flow navigation

---

app/models/flows/fluggastrechte/__test__/testcasesAnnullierung.ts
app/models/flows/fluggastrechte/context.ts
app/models/flows/fluggastrechte/guards.ts
tests/e2e/fluggastrechte.vorabcheck.spec.ts

refactor: rename annulierung -> annullierung

---

app/components/inputs/tile/TileTag.tsx
app/components/inputs/tile/__test__/TileTag.test.tsx

refactor: TileTag component 

---

app/components/RichText.tsx
app/components/StandaloneLink.tsx
app/components/__test__/StandaloneLink.test.tsx

Ticket: https://app.asana.com/0/1207022303033556/1207820849591133

Add minimal-height for standalone component

---

app/components/inputs/Select.tsx
app/components/inputs/__test__/Select.test.tsx
app/services/cms/components/StrapiDropdown.tsx

Ticket: https://app.asana.com/0/1207022303033556/1208087966238690

Feat: Define width options for Select component

---

app/flows/prozesskostenhilfeFormular/finanzielleAngaben/einkuenfte/context.ts
tests/e2e/flowPages/prozesskostenhilfe/formular/finanzielleAngabenEinkuenfte.ts
tests/fixtures/prozesskostenhilfeFormularData.ts

This PR removes the zahlungsfrequenz dropdown field for financial entries (einkunft and ausgabe)

Remove Zahlungsfrequenz field for financial entreis

---

app/flows/beratungshilfeFormular/finanzielleAngaben/doneFunctions.ts
app/flows/beratungshilfeFormular/finanzielleAngaben/guards.ts
app/flows/beratungshilfeFormular/finanzielleAngaben/hasAnyEigentumExceptBankaccountGuard.ts
app/flows/beratungshilfeFormular/stringReplacements.ts
app/flows/prozesskostenhilfeFormular/abgabe/flow.json
app/flows/prozesskostenhilfeFormular/finanzielleAngaben/context.ts
app/flows/prozesskostenhilfeFormular/finanzielleAngaben/doneFunctions.ts
app/flows/prozesskostenhilfeFormular/finanzielleAngaben/einkuenfte/__test__/doneFunctions.test.ts
app/flows/prozesskostenhilfeFormular/finanzielleAngaben/einkuenfte/context.ts
app/flows/prozesskostenhilfeFormular/finanzielleAngaben/einkuenfte/doneFunctions.ts
app/flows/prozesskostenhilfeFormular/finanzielleAngaben/einkuenfte/flow.json
app/flows/prozesskostenhilfeFormular/finanzielleAngaben/einkuenfte/guards.ts
app/flows/prozesskostenhilfeFormular/finanzielleAngaben/flow.json
app/flows/prozesskostenhilfeFormular/finanzielleAngaben/guards.ts
app/flows/prozesskostenhilfeFormular/index.ts
app/flows/shared/finanzielleAngaben/guards.ts
app/services/pdf/beratungshilfe/Handout.tsx
tests/e2e/flowPages/prozesskostenhilfe/formular/finanzielleAngabenEinkuenfte.ts
tests/fixtures/prozesskostenhilfeFormularData.ts

in the scope of commit
fix(pkh-flow): fix navigation, guards and doneFunctions around staatliche-leistungen
it is required to change the name of the select variable from `staatlicheLeistungenPKH` to `staatlicheLeistungen` in `/prozesskostenhilfe/formular/finanzielle-angaben/einkuenfte/staatliche-leistungen` in Strapi

pkh-flow fixes

---

.github/workflows/build-content.yml
.github/workflows/ci-pipeline.yml

This reverts commit 396be460b63bad7ab933f4622a23537d25dfa1a9.

Revert "feat(ci): Disable preview deployment + test in pipeline (#1123)"

---

app/components/video/Video.tsx
app/components/video/__test__/Video.test.tsx

This PR fixes the sonarlint complaints regarding Video.tsx, namely in moving inline-components to discrete children with prop passing.

refactor(Video Component sonarlint complaints)

---

app/services/validation/__test__/iban.test.ts
app/services/validation/iban.ts

Let users type lower case letters for iban and convert them to upper case automatically

feat/fgr-allow-lower-case-input-for-iban: update iban input validation

---

app/components/MigrationDataOverview.tsx
app/components/__test__/MigrationDataOverview.test.tsx
app/flows/flows.server.ts
app/flows/fluggastrechteFormular/context.ts
app/flows/fluggastrechteFormular/index.ts
app/routes/shared/components/FormFlowPage.tsx
app/routes/shared/formular.server.ts
app/services/session.server/__test__/getMigrationData.test.ts
app/services/session.server/crossFlowMigration.ts

Ticket: https://app.asana.com/0/1207022303033556/1207867714962560

Add new fields to migrate

---

app/services/cms/fetchAllFormFields.ts
app/services/session.server/__test__/getMigrationData.test.ts
app/services/session.server/crossFlowMigration.ts

- Prune data to migrate data from of Flow to another flow
- Get ApiId to fetch forms fields based the FlowId
Ticket: https://app.asana.com/0/1207022303033556/1207867714962560

Fix issues to copy data Vorabcheck

---

app/styles.css

Reverts digitalservicebund/a2j-rechtsantragstelle#1427

Revert "fix(text-link): use border-bottom due issue space safari"

---

app/components/Footer.tsx
app/components/__test__/Footer.test.tsx

Ticket: https://app.asana.com/0/1207022303033556/1208745489995869

refactor(Footer): add padding bottom 6

---

data/opensource-licenses.json
package-lock.json
package.json

Remove dependencies react-dropzone-esm and @types/sanitize-html

Remove unneeded dependencies

---

app/components/userFeedback/RatingBox.tsx
app/components/userFeedback/__test__/RatingBox.test.tsx
app/routes/$.tsx
app/routes/__test__/persoenliche-daten-loeschen.test.tsx
app/routes/_index.tsx
app/routes/action.send-feedback.ts
app/routes/action.send-rating.ts
app/routes/action.set-analytics.tsx
app/routes/beratungshilfe.tsx
app/routes/beratungshilfe.zustaendiges-gericht.auswahl.$PLZ.tsx
app/routes/beratungshilfe.zustaendiges-gericht.ergebnis.$.tsx
app/routes/data-list-options.$TYPE.ts
app/routes/feedback.erfolgreich.tsx
app/routes/fluggastrechte.tsx
app/routes/geld-einklagen.vorabcheck.partnergericht.ergebnis.$.tsx
app/routes/kitchensink._index.tsx
app/routes/opensource.tsx
app/routes/prozesskostenhilfe.tsx
app/routes/shared/visualisierung.server.ts
app/services/feedback/__test__/getRedirectForNonRelativeUrl.test.ts
app/services/feedback/getRedirectForNonRelativeUrl.ts
vite.config.ts

Reverts digitalservicebund/a2j-rechtsantragstelle#1477

Revert "Enable remix singleFetch"

---

app/domains/fluggastrechte/formular/flugdaten/__test__/doneFunctions.test.ts
app/domains/fluggastrechte/formular/flugdaten/__test__/testcasesAnnullierung.ts
app/domains/fluggastrechte/formular/flugdaten/__test__/testcasesNichtBefoerderung.ts
app/domains/fluggastrechte/formular/flugdaten/__test__/testscasesVerspaetet.ts
app/domains/fluggastrechte/formular/flugdaten/context.ts
app/domains/fluggastrechte/formular/flugdaten/doneFunctions.ts

Ticket: https://app.asana.com/0/1207022303033556/1208812977498826

Ander ersatzverbindung beschreibung optional

---

app/domains/fluggastrechte/components/SummaryDataOverview.tsx
app/domains/fluggastrechte/services/summaryPage/getOverviewData.ts

- zeugen bearbeiten link now goes to  /persoenliche-daten/weitere-personen/zeugen
- if weitere personen changed to no but zeugen yes - sentence is now "ich möchte bei Bedarf Zeugen oder Zeuginnen bennen"
Ticket:
https://app.asana.com/0/1207022303033556/1208724438567423

change-link-and-text-in-zov-summary-page for  witnesses

---

app/components/userFeedback/RatingBox.tsx
app/components/userFeedback/__test__/RatingBox.test.tsx
app/routes/$.tsx
app/routes/__test__/persoenliche-daten-loeschen.test.tsx
app/routes/_index.tsx
app/routes/action.send-feedback.ts
app/routes/action.send-rating.ts
app/routes/action.set-analytics.tsx
app/routes/beratungshilfe.tsx
app/routes/beratungshilfe.zustaendiges-gericht.auswahl.$PLZ.tsx
app/routes/beratungshilfe.zustaendiges-gericht.ergebnis.$.tsx
app/routes/data-list-options.$TYPE.ts
app/routes/feedback.erfolgreich.tsx
app/routes/fluggastrechte.tsx
app/routes/geld-einklagen.vorabcheck.partnergericht.ergebnis.$.tsx
app/routes/kitchensink._index.tsx
app/routes/opensource.tsx
app/routes/prozesskostenhilfe.tsx
app/routes/shared/visualisierung.server.ts
app/services/feedback/__test__/getRedirectForNonRelativeUrl.test.ts
app/services/feedback/getRedirectForNonRelativeUrl.ts
vite.config.ts

Reverts digitalservicebund/a2j-rechtsantragstelle#1497

Revert "Enable singleFetch"

---

app/domains/fluggastrechte/services/pdf/sections/reason/factsOfCases/compensationAmount/addCompensationAmount.ts
app/domains/fluggastrechte/services/pdf/sections/reason/factsOfCases/table/__test__/calculateDuration.test.ts
app/domains/fluggastrechte/services/pdf/sections/reason/factsOfCases/table/__test__/getConnectionDetails.test.ts
app/domains/fluggastrechte/services/pdf/sections/reason/factsOfCases/table/addTableInfo.ts
app/domains/fluggastrechte/services/pdf/sections/reason/factsOfCases/table/calculateDuration.ts
app/domains/fluggastrechte/services/pdf/sections/reason/factsOfCases/table/getConnectionDetails.ts
app/domains/fluggastrechte/services/pdf/sections/reason/legalAssessment/createLegalAssessment.ts

Ticket: https://app.asana.com/0/1207022303033556/1208585429104913

More pdf table fix

---

app/domains/fluggastrechte/vorabcheck/multiFieldsValidation.ts
app/domains/fluggastrechte/vorabcheck/services/__test__/validation.test.ts
app/domains/fluggastrechte/vorabcheck/services/validation.ts
app/domains/multiFieldsFlowValidation.ts

User can select same airports on 2 react-select component
- Add validation and throw error if the select value are same

feat: same airports will show error(s)

---

app/domains/fluggastrechte/services/pdf/__test__/userDataMock.ts
app/domains/fluggastrechte/services/pdf/sections/firstPage/claimData/__test__/addAirlineDetails.test.ts
app/domains/fluggastrechte/services/pdf/sections/firstPage/claimData/addAirlineDetails.ts

Ticket: https://app.asana.com/0/1207022303033556/1209116568805949

Add airline address pdf

---

app/domains/fluggastrechte/services/pdf/sections/reason/factsOfCases/table/__test__/getConnectionDetails.test.ts
app/domains/fluggastrechte/services/pdf/sections/reason/factsOfCases/table/getConnectionDetails.ts

Ticket: https://app.asana.com/0/1207022303033556/1209160538617440

refactor(getConnectionDetails): add annullierung dates info

---

app/domains/fluggastrechte/components/ActualArrivalCards.tsx

Ticket: https://app.asana.com/0/1207022303033556/1209116568805956

refactor(ActualArrivalCards): add annullierung data on overview page

---

app/components/inputs/Checkbox.tsx
app/components/inputs/__test__/Checkbox.test.tsx

| Error | Default |
|---------|---------|
| ![Before Image 1](https://github.com/user-attachments/assets/44d6c5ef-9696-4820-9318-7c5e81ae9b2f) | ![Before Image 2](https://github.com/user-attachments/assets/c53d1c14-062f-48a7-9caf-2f3159eca67d) |
| Error | Default | Error | Default |
|---------|---------|---------|---------|
| ![After Image 1](https://github.com/user-attachments/assets/bb20941e-c8d8-4b71-a3ec-2c1a9ebd261c) | ![After Image 2](https://github.com/user-attachments/assets/6f41834c-c671-4e96-9a61-35fccb055e55) | ![After Image 3](https://github.com/user-attachments/assets/39669b35-e6a8-411b-89f6-b0a907849634) | ![After Image 4](https://github.com/user-attachments/assets/fdbb6c37-cea4-44d2-ac91-d2325415f524) |

feat: checkbox aligns vertically

---

README.md

I'm not sure why I can't create this commit directly without bypassing the rules.

Update README.md for airline data source

---

doc/adr/0020-single-a2j-otc-bucket-instance.md

interesting commit message / sorry

docs(adr): create a single a2j otc bucket instance

---

app/domains/fluggastrechte/formular/__test__/stringReplacements.test.ts
app/domains/fluggastrechte/formular/grundvoraussetzungen/__test__/testcases.ts
app/domains/fluggastrechte/formular/grundvoraussetzungen/flow.json
app/domains/fluggastrechte/formular/index.ts
app/domains/fluggastrechte/formular/streitwertKosten/flow.json
app/domains/fluggastrechte/formular/stringReplacements.ts
tests/e2e/domains/fluggastrechte/formular/startFluggastrechteFormular.ts

Ticket: https://app.asana.com/0/1207022303033556/1209203285746908

Add page amtsgericht

---

app/components/MigrationDataOverview.tsx
app/components/__test__/MigrationDataOverview.test.tsx

Ticket: https://app.asana.com/0/1207022303033556/1209287041640893

Render a cta component

---

app/domains/fluggastrechte/components/StreitbeilegungCard.tsx
app/domains/fluggastrechte/components/SummaryDataOverview.tsx

added sentences as described in this [ticket](https://app.asana.com/0/1207022303033556/1209254932670922)

add außergerichtliche Streitbeteiligung to summary page

---

app/domains/schulden/vorabcheck/__test__/xStateConfig.test.ts
app/domains/schulden/vorabcheck/xStateConfig.ts

- Get rid of nested state objects 
- refactor unit tests

feat: flatten state and update unit tests

---

app/components/form/ValidatedFlowForm.tsx

remove space between Paragraph and action buttons ("Zurück", "Weiter") in case of non-form component is rendering

conditional styling to remove unused margins in a non-form Strapi component

---

app/domains/fluggastrechte/formular/flugdaten/context.ts
app/domains/fluggastrechte/formular/services/__test__/validation.test.ts
app/domains/fluggastrechte/formular/services/validation.ts

https://app.asana.com/0/1207022303033556/1209508287228460

feat: validate input when any of the field is filled

---

app/components/inputs/Radio.tsx

https://app.asana.com/1/1146679785927162/project/1207022303033556/task/1208984340607666
| State  | Screenshot                                                                 |
|--------|----------------------------------------------------------------------------|
| Before | <img src="https://github.com/user-attachments/assets/de69870d-c677-4ff1-bff6-bc7590f97bc3" width="720"> <img src="https://github.com/user-attachments/assets/caec2d0d-8fe4-45e9-9d20-f04d52c249aa" width="720"> |
| After  | <img src="https://github.com/user-attachments/assets/ac4534b0-06ec-40d4-ac57-bb5f53562c0c" width="720"> <img src="https://github.com/user-attachments/assets/1ac54885-81b9-4614-b2f3-6b0a09cc0183" width="720"> |

feat(a11y): use default high-contrast mode for Radio

---

app/services/security/markdownUtilities.tsx

feat: allow class attribute for Description Term element

---

app/domains/prozesskostenhilfe/formular/index.ts
tests/e2e/domains/prozesskostenhilfe/formular/abgabe.ts
tests/e2e/domains/prozesskostenhilfe/formular/prozesskostenhilfe.formular.spec.ts

This PR implements a files upload page to the PKH flow

feat(PKH): add files upload page to PKH

---

app/routes/__test__/hilfe.test.tsx
app/routes/hilfe.tsx

Ticket: https://app.asana.com/1/1146679785927162/project/1207022303033556/task/1208775058297140

Redirect to kontakt page

---

app/components/inputs/autoSuggestInput/AutoSuggestInput.tsx
app/components/inputs/autoSuggestInput/__test__/AutoSuggestInput.test.tsx
app/components/inputs/autoSuggestInput/customComponents/CustomInput.tsx
app/components/inputs/autoSuggestInput/types.ts
app/services/cms/components/StrapiAutoSuggestInput.ts
stories/AutoSuggestInput.stories.tsx

Ticket: https://app.asana.com/1/1146679785927162/project/1207022303033556/task/1209211310360737

Add aria required auto suggest input

---

app/root.tsx

Since the link is already in the LinksFunction I removed the second one

remove double stylesheet link

---

app/components/Hero.tsx
app/components/PageContent.tsx
app/components/__test__/Hero.test.tsx
app/services/cms/models/StrapiContentComponent.ts
app/services/cms/models/StrapiHeading.ts
app/services/cms/models/StrapiHero.ts
app/services/cms/models/__test__/StrapiHero.test.ts
app/services/cms/models/isStrapiHeader.ts
app/services/cms/models/isStrapiHero.ts
app/services/meta/metaFromMatches.ts
stories/Header.stories.tsx

Ticket: https://digitalservicebund.atlassian.net/browse/ZOV-52

Rename component header to hero

---

app/domains/beratungshilfe/formular/abgabe/dokumente/context.ts
app/domains/beratungshilfe/formular/index.ts
app/domains/beratungshilfe/formular/stringReplacements.ts
app/domains/beratungshilfe/services/pdf/userUploadedFiles/attachUserUploadedFilesToPdf.ts

This PR implements the optional document upload field, enabling the user to upload other files or leaving it empty without getting required error message

feat(BerH): enable optional document upload field

---

app/domains/prozesskostenhilfe/formular/abgabe/dokumente/userData.ts
app/domains/prozesskostenhilfe/formular/abgabe/stringReplacements.ts
app/domains/prozesskostenhilfe/formular/userData.ts

This PR implements a Dokumente userData data to PKH Abgabe

feat(PKH Files Upload): add dokumente userData

---

app/domains/prozesskostenhilfe/formular/abgabe/dokumente/userData.ts
app/domains/prozesskostenhilfe/formular/index.ts
app/domains/prozesskostenhilfe/formular/stringReplacements.ts
app/domains/prozesskostenhilfe/formular/userData.ts
tests/e2e/domains/beratungshilfe/formular/beratungshilfe.formular.spec.ts
tests/e2e/domains/prozesskostenhilfe/formular/abgabe.ts
tests/e2e/domains/prozesskostenhilfe/formular/prozesskostenhilfe.formular.spec.ts

This PR fixes ProzesskostenhilfeDokumenteUserData name, fix import in the formular index

feat(PKH Files Upload): add correct schema & e2e test

---

tests/e2e/domains/prozesskostenhilfe/formular/prozesskostenhilfe.formular.spec.ts

This PR add back the assertion for the abgabe in PKH

test(PKH Files Upload): uncomment abgabe assertion

---

app/components/inputs/FileInput.tsx
app/components/inputs/__test__/FileInput.test.tsx

Upload button is taking way more width than it needs

[Fix] PKH and BerH page over-scroll

---

app/domains/fluggastrechte/formular/flugdaten/userData.ts
app/domains/fluggastrechte/formular/services/validation/__test__/validateCancelFlightReplacementPage.test.ts
app/domains/fluggastrechte/formular/services/validation/validateCancelFlightReplacementPage.ts

text inputs return empty string `""` [when not filled out](https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/input/text#value).
-> removes `.optional()` on annulierungs fields and test against empty string instead of `undefined`

feat(FGR userData): remove .optional and test for empty string

---

app/components/navigation/SideNavMobile.tsx
app/components/navigation/__test__/SideNavMobile.test.tsx

Ticket: https://digitalservicebund.atlassian.net/browse/ZOV-497

Set the aria-expanded with the correct value

---

doc/adr/0025-layout-grids.md

This is the final ADR for the grids, design provided us with the first screen to test this on here: https://www.figma.com/design/ZH3eHFYs3qpoN7jklyrQxW/KERNFusion?node-id=219-20809&t=YzQu8huvEVfIZqlL-0

RAST-197 Layout grid ADR

---

app/domains/beratungshilfe/formular/finanzielleAngaben/pages.ts
app/domains/beratungshilfe/formular/finanzielleAngaben/partner/guards.ts
app/domains/beratungshilfe/formular/finanzielleAngaben/partner/pages.ts
app/domains/beratungshilfe/formular/finanzielleAngaben/partner/userData.ts
app/domains/beratungshilfe/formular/finanzielleAngaben/partner/xstateConfig.ts
app/domains/beratungshilfe/formular/finanzielleAngaben/userData.ts
app/domains/beratungshilfe/formular/finanzielleAngaben/xstateConfig.ts

This PR moves BerH Finanziellen Angeben Partner to pageSchemas

refactor: move BerH Finanziellen Angaben Partner to pageSchemas

---

app/domains/beratungshilfe/formular/finanzielleAngaben/pages.ts
app/domains/beratungshilfe/formular/finanzielleAngaben/regelmaessigeAusgaben/pages.ts
app/domains/beratungshilfe/formular/finanzielleAngaben/regelmaessigeAusgaben/userData.ts
app/domains/beratungshilfe/formular/finanzielleAngaben/regelmaessigeAusgaben/xstateConfig.ts
app/domains/beratungshilfe/formular/finanzielleAngaben/userData.ts
app/domains/beratungshilfe/formular/finanzielleAngaben/xstateConfig.ts

This PR refactors BerH Finanziellen Angaben Regelmäßiges Angaben to pageSchemas

refactor(BerH): move BerH Finanziellen Angaben Regelmäßiges Angaben to pageSchemas

---

app/domains/beratungshilfe/formular/__test__/testcases.ts
app/domains/beratungshilfe/formular/persoenlicheDaten/xstateConfig.ts
app/domains/beratungshilfe/formular/xstateConfig.ts
app/services/isFeatureFlagEnabled.server.ts
tests/e2e/domains/beratungshilfe/formular/persoenlicheDaten.ts

this feature flag is fully rolled out
after merge: remove flags on all posthog instances

chore(featureFlag): remove 'showNachbefragung'
