app/components/form/steps/einkommen.tsx
app/components/form/steps/einkommenKinder.tsx
app/components/form/steps/einkommenPartner.tsx
app/components/form/steps/miete.tsx
app/components/form/steps/unterhaltSumme.tsx
app/components/form/steps/weitereZahlungenSumme.tsx
app/lib/freibetrag.ts
app/lib/vorabcheck/flow.server.ts
app/services/validation/money/buildMoneyValidationSchema.ts
app/services/validation/money/formatCents.ts
app/services/validation/money/moneyToCents.ts
app/services/validation/money/preprocessMoney.ts
app/services/validation/money/validateMoney.ts
package-lock.json
package.json
tests/unit/services/validation/money/buildMoneyValidationSchema.test.ts
tests/unit/services/validation/money/formatCents.test.ts
tests/unit/services/validation/money/moneyToCents.test.ts
tests/unit/services/validation/money/preprocessMoney.test.ts
tests/unit/services/validation/money/validateMoney.test.ts

Money is no longer a float, but a string and must be converted to cents (integer) before doing arithmetic.

Add validations for money (euro) input fields

---

.github/workflows/ci-pipeline.yml
Dockerfile
README.md
package-lock.json
package.json

Node 16 has EOL in September 23, and our first dependency (`Marked`) got bumped to a min version of 18.
Also replaces https://github.com/digitalservicebund/a2j-rechtsantragstelle/pull/97

Update to node v18

---

.github/actions/production-text-test/action.yml
.github/actions/production-text-test/test-text.sh
.github/workflows/ci-pipeline.yml
.prettierignore

note:
- error was thrown: `[error] No parser could be inferred for file ".github/actions/production-text-test/test-text.sh".`
I excluded `.sh` because of missing a prettier parser 
- The curl request won't trigger a tracking event 👍

chore: remove basic http authentication

---

app/components/PageContent.tsx
app/components/inputs/Checkbox.tsx
app/services/cms/models/StrapiCheckbox.tsx
app/services/cms/models/StrapiContent.ts
app/services/cms/models/StrapiFormComponent.ts
app/services/validation/checkedCheckbox.ts
tests/unit/components/__snapshots__/storybook.test.ts.snap

Proposal: Mapping the CMS component to React component inside the function (see `renderCheckboxFromStrapi()`) rather than mapping the props

feat(StrapiFormComponents): add StrapiCheckbox

---

app/routes/action.send-rating.ts
app/routes/shared/step.tsx
app/services/analytics/customEvent.ts
app/services/analytics/posthogClient.server.ts
app/services/feedback/handleFeedback.ts
app/services/flow/buildFlowController.ts

- adds `sendCustomEvent()`
- tries to extract `distinct_id` from posthog cookie, otherwise falls back to `ENVIRONMENT`
- ~⚠️ currently sends ANY submitted step data ⚠️~
TODO

feat(tracking): add custom events with distinct id

---

app/routes/action.send-rating.ts
app/routes/action.set-analytics.tsx
app/routes/cookie-einstellungen.tsx
app/routes/shared/step.server.ts
app/services/analytics/customEvent.ts
app/services/analytics/gdprCookie.server.ts
app/services/feedback/handleFeedback.ts

Actually I just wanted to quickly add the event to the cookie-consent, then I tried to standardize the event handling. Feedback appreciated 🙏😁

feat(posthog): add custom event for cookie consent and unify event handling

---

.github/workflows/build-content.yml
.github/workflows/ci-pipeline.yml

As mentioned [here](https://digitalservicebund.slack.com/archives/C03M9TZTDK8/p1710341286056739), we have to split our internal GitHub actions repo. This PR update your CI configuration to point to the new repositories. Please, review and merge this PR. Don't hesitate to contact the Platform team if you run into any issue.

chore: Internal GitHub Action migration

---

package-lock.json
package.json
server.js

The `*/pdf` route is quite expensive and will burn the CPU before any network-level rate limiting catches on.
This will allow only 2 calls per 2 seconds, happy to discuss better defaults here.
My reasoning was that this will allow the odd miss-click but effectively throttles any malicious request to 1 per second

feat(pdf): introduce rate limiting

---

app/components/UserFeedback/FeedbackFormBox.tsx
app/components/UserFeedback/FeedbackTranslationContext.tsx
app/components/UserFeedback/PostSubmissionBox.tsx
app/components/UserFeedback/RatingBox.tsx
app/components/UserFeedback/__test__/FeedbackFormBox.test.tsx
app/components/UserFeedback/__test__/PostSubmissionBox.test.tsx
app/components/UserFeedback/__test__/RatingBox.test.tsx
app/components/UserFeedback/__test__/UserFeedback.test.tsx
app/components/UserFeedback/index.tsx
app/components/resultPage/ResultPage.tsx
app/root.tsx
stories/UserFeedback.stories.tsx

Today we have hardcode the texts/descriptions of the User feedback component. We are moving those texts/descriptions to Strapi Translations
- Move texts/descriptions to Strapi Translation
- Create a context with the feedback translations
- Use hook to get the feedback translations without pass them via props
Later we will have this component also in Strapi, so using the context and hook it would be easier to make the component following the Product and UX requirements

Add translations user feedback

---

app/components/Button.tsx
app/components/CourtDetails.tsx
app/components/StandaloneLink.tsx
app/components/__test__/StandaloneLink.test.tsx
app/services/openSourceLicenses/LicenseList.tsx
stories/StandaloneLink.stories.tsx

My very first contribution 🎉 🥳 
This PR adds the Standalone Link component, as well as Storybook and tests.
https://app.asana.com/0/1203259475859667/1207931106219834/f
Demo: (Visually identical 😆 )
Demo: (Left Icon added)

Add Standalone Link Component

---

app/components/inputs/__test__/Input.test.tsx
app/components/inputs/__test__/Select.test.tsx
app/components/inputs/width.ts
app/routes/shared/components/FormFlowPage.tsx
app/styles.css

On the Formular pages for mobile and tables, when an input is selected 54 characters, it jumps to the bottom of the page.
More info in the following slack [link](https://digitalservicebund.slack.com/archives/C044NUG2468/p1726160178710569)
Change width to max-width

Fix input to large devices

---

app/components/StandaloneLink.tsx
app/components/__test__/StandaloneLink.test.tsx

This PR fixes a styling bug where link list items with a newline would display the bullet point at the bottom, instead of at the top, of the list item.
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1208311653825044

fix(List links bullet point styling)

---

app/services/validation/postcode.ts
package.json
scripts/unusedStrapiEntries.ts

https://app.asana.com/0/1203259475859667/1208196006606406/f
- scans all xstate configs to recursively build URLs
- parses URLs from all form-flow-, vorabcheck-, result-pages (from content file)
- compares and returns all URLs that aren't referenced in xstate configs
- additionally prints pages without stepId

feat(scripts): npm run verify:unusedStrapiEntries

---

tests/e2e/flowPages/beratungshilfe/formular/anwaltlicheVertretung.ts
tests/e2e/flowPages/beratungshilfe/formular/finanzielleAngabenAusgaben.ts
tests/e2e/flowPages/beratungshilfe/formular/finanzielleAngabenEigentum.ts
tests/e2e/flowPages/beratungshilfe/formular/finanzielleAngabenEinkommen.ts
tests/e2e/flowPages/beratungshilfe/formular/finanzielleAngabenWohnung.ts
tests/e2e/flowPages/beratungshilfe/formular/grundvoraussetzungen.ts
tests/e2e/flowPages/beratungshilfe/formular/persoenlicheDaten.ts
tests/e2e/flowPages/beratungshilfe/formular/rechtsproblem.ts
tests/e2e/flowPages/fluggastrechte/formular/startFluggastrechteFormular.ts
tests/e2e/flowPages/fluggastrechte/vorabcheck/vorabcheckAnnullierung.ts
tests/e2e/flowPages/fluggastrechte/vorabcheck/vorabcheckNichtBefoerderung.ts
tests/e2e/flowPages/fluggastrechte/vorabcheck/vorabcheckVerspaetung.ts
tests/e2e/flowPages/geldEinklagen/formular/geldeinklagen.formular.spec.ts
tests/e2e/flowPages/geldEinklagen/vorabcheck/geldeinklagen.vorabcheck.spec.ts
tests/e2e/flowPages/prozesskostenhilfe/formular/antragstellendePerson.ts
tests/e2e/flowPages/prozesskostenhilfe/formular/finanzielleAngabenAusgaben.ts
tests/e2e/flowPages/prozesskostenhilfe/formular/finanzielleAngabenEigentum.ts
tests/e2e/flowPages/prozesskostenhilfe/formular/finanzielleAngabenEinkuenfte.ts
tests/e2e/flowPages/prozesskostenhilfe/formular/finanzielleAngabenEinkuenftePartner.ts
tests/e2e/flowPages/prozesskostenhilfe/formular/gesetzlicheVertretung.ts
tests/e2e/flowPages/prozesskostenhilfe/formular/grundvoraussetzungen.ts
tests/e2e/flowPages/prozesskostenhilfe/formular/persoenlicheDaten.ts
tests/e2e/flowPages/prozesskostenhilfe/formular/prozesskostenhilfe.formular.spec.ts
tests/e2e/flowPages/prozesskostenhilfe/formular/rechtsschutzversicherung.ts
tests/e2e/flowPages/shared/finanzielleAngaben/finanzielleAngabenAndereUnterhaltszahlungen.ts
tests/e2e/flowPages/shared/finanzielleAngaben/finanzielleAngabenEigentumZusammenfassung.ts
tests/e2e/flowPages/shared/finanzielleAngaben/finanzielleAngabenKinder.ts
tests/e2e/flowPages/shared/finanzielleAngaben/finanzielleAngabenPartner.ts

- Remove accessibility tests of all the Formular pages
- Keep the accessibility tests on start, abgabe and übersicht pages
- Remove accessibility tests of Vorabcheck Fluggasterechte and Geldeinklage

Both streams: Remove accessibility tests of forms flow pages

---

lefthook.yml

This PR moves the unit tests command to the `pre-push` stage (instead of `pre-commit`), as our unit tests are growing ever larger and it's annoying to run them for every commit.
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1208674492323937

refactor(move unit tests to pre-push git hook)

---

app/styles.css

- Use border-bottom instead of text-decoration-thickness to not add space to the box and avoid issues in Safari
Ticket: https://app.asana.com/0/1207022303033556/1208745489995869

fix(text-link): use border-bottom due issue space safari

---

.github/actions/cached-checkout-install/action.yml

Remove the `restore-keys` option, so we only get the cache from the key. I have noticed sometimes we are getting a node-module cache in dependent bot PRs, even we have a new dependency update.

Remove restore-keys

---

app/domains/prozesskostenhilfe/services/pdf/pdfForm/G_eigentum.ts
eslint.config.js

I could only reproduce this bug with the arc browser. The root cause were two titles in `bargeld` and `wertsachen` where the 'ü' of `Eigentümer:in` was written as a NFD (normalized form canonical decomposition) which means the 'u' was typed first, followed by the combining diacritical marks. `pdfkit` does not seem to properly support encoding these characters in few cases (arc browser).
Proposal: Added a linter rule that detects NFDs.
https://app.asana.com/0/1203259475859667/1208834671333919

fix(pdf-service): fix bug with German umlauts not rendered correctly in pdf

---

lefthook.yml

Linting now takes quite a bit of time due to requiring a typescript build
suggestion:
- move linting hook from pre-commit to pre-push
- run in parallel to unit tests
reason: we probably all have linting set up in our IDEs, the hook should just be a failsafe

chore(lefthook): move lint to pre-push

---

app/components/Footer.tsx
app/components/Image.tsx
app/services/cms/models/StrapiImage.ts
app/services/cms/models/__test__/StrapiImage.test.ts
app/services/security/cspHeader.server.tsx
package-lock.json
package.json

This PR ensures that SVGs are displayed as inline components for accessibility, specifically with high-contrast display modes.

fix(BMJ Logo Accessibility)

---

app/components/BoxWithImage.tsx
app/components/__test__/BoxWithImage.test.tsx
app/services/cms/models/StrapiBoxWithImage.ts
stories/BoxWithImage.stories.tsx

This PR modififes the BoxWithImage component to have a simpler interface, styling, and to support new size options, while preserving backwards-compatibility
- **modify BoxWithImage and storybook to align with new size specifications**
- **simplify variantWidths interface, add unit test**

refactor(BoxWithImage component)

---

tests/e2e/critical/homepage.spec.ts

The current test to check if the logo of BMJ was available on the homepage was not working with the command `.getByRole("img")` anymore.
Get the logo by the parent parent using the selector Id `#BMJ-Logo-Banner`

refactor(homepage): get logo by div parent parent

---

.github/workflows/e2e-test.yml
tests/e2e/common/userfeedback.vorabcheck.spec.ts
tests/e2e/domains/fluggastrechte/formular/startFluggastrechteFormular.ts

The E2E Tests were running with the command `` npm run test:e2e -- false ``, due the wrong condition on `e2e-test.yml` file.
Add the `else` condition with `||` to avoid the word `false` on the command.

Ci: run e2e test for non preview

---

app/domains/__test__/flows.test.ts
app/domains/prozesskostenhilfe/formular/__test__/testcases.ts
app/domains/prozesskostenhilfe/formular/rechtsschutzversicherung/__test__/testcases.ts

We have a few flow steps (mostly warning or array pages) that are not reachable using the `BACK` event. therefore, they can't really be tested inside a flow-test. I propose a forward-only test to at least cover the existing transition

test(pkh flow): add forward-only flow tests

---

app/domains/fluggastrechte/formular/flugdaten/context.ts
app/services/validation/__test__/optionalOrSchema.test.ts
app/services/validation/optionalOrSchema.ts

For the FGR case, we need to set the value of the `annullierung` schema to an empty string, as it is optional.

feat: allow to pass alternative schema

---

app/components/cookieBanner/CookieBanner.tsx

This PR implements maskTextSelector to session recording in posthog init. It prevents sensitive data being shown in summary/array pages

fix(Posthog Capture Text): add maskTextSelector to PostHog init

---

app/components/cookieBanner/CookieBanner.tsx

This PR implements maskAllInputs to session recording in posthog init. It prevents sensitive data being shown on pages

fix(Posthog Capture Text): add maskAllInputs to session record for maximum privacy

---

app/components/List.tsx
app/components/ListItem.tsx
app/components/__test__/ListItem.test.tsx

- adds new `stepByStep` variant to `<List />`
- adds some missing component tests
- fixes some gaps
- moves some alignments from margin / padding to flexbox
Storybook screenshot:

feat(List): add new stepByStep variant

---

app/services/validation/__test__/iban.test.ts
app/services/validation/iban.ts
data/opensource-licenses.json
package-lock.json
package.json

- as in title: replaces `ibantools` with existing `validator/iban`
- moves an invalid IBAN to failing tests

refactor(iban): replace ibantools by validator/iban

---

app/components/navigation/FlowNavigation.tsx
app/routes/shared/components/FormFlowPage.tsx

(bug): Sidenav should be 248 px ([Ticket](https://app.asana.com/0/1203259475859667/1209657702141639/f))

fix: adjust Sidenav menu width

---

app/domains/kontopfaendung/wegweiser/__test__/stringReplacements.test.ts
app/domains/kontopfaendung/wegweiser/__test__/testcases.ts
app/domains/kontopfaendung/wegweiser/context.ts

This PR removes the checkbox option "nichts trifft zu" from sozialleistungenUmstaende

fix(Wegweiser): remove nichts trifft zu option from sozialleistungenUmstaende

---

app/domains/prozesskostenhilfe/services/pdf/__test__/printNameInSignatureFormField.test.ts
app/domains/prozesskostenhilfe/services/pdf/index.ts
app/domains/prozesskostenhilfe/services/pdf/printNameInSignatureFormField.ts

This PR fixes the PDF generation with special characters:
- Register fontkit with PDFDocument in the printNameInSignatureFormField to allow pdf to be generated with special characters like "ń"

bug(PKH): allow PDF generation with special characters 

---

app/services/security/__test__/markdownUtilities.test.ts
app/services/security/markdownUtilities.tsx

Well that was annoying.
Fix handleNestedLists postfixer to correctly un-nest opening list tags outside of mustache conditionals to ensure accessibility-compliant, syntactically-correct html
- **vastly simplify nested list logic**
- **adapt unit test, adapt function to handle inverted condtions too**

fix(Strapi List HTML Bug)

---

.github/workflows/ci-pipeline.yml
.github/workflows/npm-checks.yml
app/services/validation/stepValidator/__test__/schemaForFieldNames.test.ts

test w coverage with included sonarcube blocks the pipeline for ~4 minutes
test with coverage takes about ~2 min, sonarcube runs by itself without blocking further deployment

refactor(ci): parallel sonarcloud-scan job

---

app/services/analytics/__test__/useInitPosthog.test.ts
app/services/analytics/useInitPosthog.ts

The current posthog behavior:
- main bundle is always loaded (even when declining cookies)
- surveys bundle is dynamically fetched from external
After this change:
- main bundle is loaded dynamically if needed (reduces JS load if cookies are declined)
- survey bundle is immediately served from our server (enables parallelism & bundling)
(note the url for surveys)

feat(posthog): dynamic import

---

app/routes/beratungshilfe.zustaendiges-gericht.auswahl.$PLZ.tsx

This PR fixes the Report Problem spacing on the auswahl page by wrapping the container and button in a div
Before
After

bug(Report Problem): wrap container and report problem in a div

---

app/domains/fluggastrechte/vorabcheck/__test__/testCasesFluggastrechteVorabcheck.ts
app/domains/fluggastrechte/vorabcheck/__test__/testcasesNichtBefoerderungAbbruch.ts
app/domains/fluggastrechte/vorabcheck/__test__/testcasesNichtBefoerderungErfolg.ts
app/domains/fluggastrechte/vorabcheck/xstateConfig.ts

Given I am on the “Vorab-Check” for case type “Nicht-beförderung”
- When I answer “Ja” on the “vertretbare Gründe” page `/vorabcheck/vertretbare-gruende`
- Then I am redirected to the “vertretbare Gründe Info” page `/vorabcheck/vertretbare-gruende-info`
- And the old abort page `/vorabcheck/ergebnis/vertretbare-gruende-abbruch` is removed
- And I continue to the “Verjährung” page `/vorabcheck/verjaehrung`
- When I answer “Nein” on the “vertretbare Gründe” page `/vorabcheck/vertretbare-gruende`
- Then I remain on the normal flow and proceed to the “Verjährung” page `/vorabcheck/verjaehrung`

feat(ZOV): no more vertretbare-gruende-abbruch page

---

app/components/inputs/autoSuggestInput/customComponents/FormatOptionLabel.tsx
app/components/inputs/autoSuggestInput/customComponents/__test__/FormatOptionLabel.test.tsx

We only escape parentheses, which break whenever someone types `?`, `+`, `.` or any other regex special character. 
- Added `lodash.escapeRegExp` to escape all regex-meta chars.
- Updated splitHighlightWord to use it instead of our old helper.
- Expanded test suite with other special characters

Bugfix: Use lodash.escapeRegExp for safer regex escaping
